trigger: none

# Schedule to run overnight
schedules:
- cron: "0 20 * * *"
  displayName: Daily overnight build
  branches:
    include:
    - develop
    
# Include shared variables
variables:
- template: shared-variables.yml

resources:
  repositories:
  - repository: ciTemplates # Id of the repository used to reference to in this script
    type: git
    name: common-ci # Name of the actual repository

stages:
- template: shared-build-and-test-platforms.yml
  parameters:
    windowsImage: $(windowsImage)
    linuxImage: $(linuxImage)
    macImage: $(macImage)

# Try to complete the corresponding pull request if
# this is triggered by one.    
- template: shared-auto-complete-pr-stage.yml@ciTemplates