# Disable automatic runs of this pipeline when changes are pushed to the repository.
trigger: none

# Disable automatic runs of this pipeline when a PR is create.
pr: none

# Add the pipeline that builds the packages as a resource.
# This allows the deployment pipeline to be triggered whenever
# the build pipeline completes.
# Add common-ci repo as a resource to access common templates.
resources:
  pipelines:
  - pipeline: build-pipeline   # The name for the triggering build pipeline within this script
    source: pipeline-python-create-packages # Name of the pipeline
    trigger: true
    
# Include shared variables
variables:
- template: shared-variables.yml
- name: targetBranch
  value: 'refs/heads/master'
  
stages:
- stage: publish_internal
  displayName: Publish Internal
  jobs:
  # Note - A 'deployment' job will automatically download the artifacts created by the triggering pipeline.
  - deployment: deploy_internal
    displayName: Deploy Internal
    pool:
      vmImage: $(linuxImage)
      workspace:
        clean: all
    environment: packages-internal
    strategy:
      runOnce:
        deploy:
          steps:
    
          - template: shared-publish-packages.yml
            parameters:
              publishEndpoint: 'pipeline-insider'